version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: gorm
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: gorm
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gorm"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
